---
- hosts: all
  tasks:
- yum:
    name: httpd
    state: latest
- copy:
    src: /sourcecode/
    dest: /var/www/html

- firewall:
      port: 8080/tcp
      permanent: true
      state: enabled
      immediate: true

- service:
      name: httpd
      state: started
      
    
